### ISSUE TITLE
edge-remover fails to remove Edge on recently updated Windows

### ISSUE THREAD

**Issue by WayneSherman** [jbara2002/edge-remover#13] opened 2022-11-19 21:09 UTC
I tested your script on Win10 Pro 21H2 and Win10 IoT Ent 2021 (21H2) LTSC.  It works on a 2022-May updated Win10 Pro and it works on a 2022-Mar updated Win10 IoT.  But it fails to work on a  2022-Oct updated Win10 Pro and also fails on a 2022-Nov updated Win10 IoT.

I suspect Microsoft update(s) between 2022-May and 2022-Oct have caused the removal script to stop working.  Other scripts have also stopped working that used to work.

On the older snapshots of Windows if I remove Edge first, before doing any updates, and then perform Win updates the updates are successfully applied and Edge stays removed.

See here:
https://github.com/AveYo/fox/issues/26
https://github.com/ShadowWhisperer/Remove-Edge-Chromium/issues/9
https://github.com/CodingMommy/EdgeRemover/issues/1

**Comment by jbara2002** [comment] 2022-11-25 05:49
Same thing with OneDrivebin lastest versions. It became inuninstallable. I'll try to work for new methods to remove that.
The next launch of the Edge Remover and OneDrive Uninstaller is mid-Dec.

**Comment by jbara2002** [comment] 2022-11-25 05:51
So before of that, i'll announcing for testing workarounds, before release.

**Comment by jbara2002** [comment] 2022-11-25 12:25
Update: Installing Edge 107 as MSI Package and removing with the created ".msi" file from C:\Windows\Installer(hidden folder) it works,but normal methodes are untested.

**Comment by Jamskijam** [comment] 2022-12-19 19:08
https://github.com/ShadowWhisperer/Remove-Edge-Chromium/issues/9#issuecomment-1356898491

**Comment by jbara2002** [comment] 2023-01-11 11:01
you can test now 
https://github.com/jbara2002/edge-remover/releases/tag/release2.0 
I will close this issue until complete removal it will work.

**Comment by WayneSherman** [comment] 2023-01-11 17:50
Both the "edge_remover.bat" and "Edge.Remover.exe" work on Win10 Pro 21H2 with Windows updates as of 2022-May-03.  But both of them fail to remove Edge on Win10 Pro 22H2 with Windows updates as of 2022-Dec-20.  Also running Edge.Remove.exe a second time (after I rebooted) causes a .NET unhandled exception.

Although I don't mind testing the EXE version in a sandbox, I would not use it in production.  Does it do the same things as the batch file?

**Comment by jbara2002** [comment] 2023-01-12 16:39
the batch file cannot run single. it needs some additional permission to remove things from C:\Program Files. UWP Edge (Legacy) Removal works fine.

**Comment by WayneSherman** [comment] 2023-01-12 16:43
> it needs some additional permission
When I tested, I ran them as administrator (elevated).

**Comment by caspertone2003** [comment] 2023-01-15 01:12
@jbara2002 
Hi,
I am trying to use the V2 exe, in a lean 21H2.
I started my trials with Edge 108.0.1462.76.
First thing I found was the classic setup.exe etc.; no success.
I tried then after with AveYo bat, no success.
I tried with your v2 exe, no success, as I got an execution error before the gui, but I tried anyhow.
After, I run your bat. Got rid of Edge but remained leftovers, such as folders EdgeCore, EdgeUpdate and EdgeWebView. as well as icons, and presence in intalled apps/programs info.
After cleaning registry and program removal, etc., reinstalled Edge and WebView, so to check from a clean status. Got 109.0.1518.52. Suffered until I removed execution blocking (that either your exe or bat puts probably in the registry - this should be optional as for example I use a portable edge from time to time and blocking is an issue) - I handle blocking with Sordum Edge blocker (portable).

Tested again v2 exe. Continues rising an error before gui (this time I killed).

Perhaps can you help to find out with file I am missing?

Follows trace:

**** exception ******
System.ComponentModel.Win32Exception (0x80004005): system cannot find specified file
   in System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   in System.Diagnostics.Process.Start()
   in Edge_Remover.Form1.Form1_Load(Object sender, EventArgs e)
   in System.Windows.Forms.Form.OnLoad(EventArgs e)
   in System.Windows.Forms.Form.OnCreateControl()
   in System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   in System.Windows.Forms.Control.CreateControl()
   in System.Windows.Forms.Control.WmShowWindow(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   in System.Windows.Forms.Form.WmShowWindow(Message& m)
   in System.Windows.Forms.Form.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

follows a list of loaded modules:
mscorlib
Edge Remover
System.Windows.Forms
System
System.Drawing
System.Configuration
System.Core
System.Xml
System.Windows.Forms.resources
mscorlib.resources

Perhaps is it NET48REL1? (missing in my system?)
just installed it.
I will report back after restart ....

**Comment by caspertone2003** [comment] 2023-01-15 01:47
@jbara2002 
Hi,
I am trying to use the V2 exe, in a lean 21H2.
I started my trials with Edge 108.0.1462.76.
First thing I found was the classic setup.exe etc.; no success.
I tried then after with AveYo bat, no success.
I tried with your v2 exe, no success, as I got an execution error before the gui, but I tried anyhow.
After, I run your bat. Got rid of Edge but remained leftovers, such as folders EdgeCore, EdgeUpdate and EdgeWebView. as well as icons, and presence in intalled apps/programs info.
After cleaning registry and program removal, etc., reinstalled Edge and WebView, so to check from a clean status. Got 109.0.1518.52. Suffered until I removed execution blocking (that either your exe or bat puts probably in the registry - this should be optional as for example I use a portable edge from time to time and blocking is an issue) - I handle blocking with Sordum Edge blocker (portable).

Tested again v2 exe. Continues rising an error before gui (this time I killed).

Perhaps can you help to find out with file I am missing?

Follows trace:

**** exception ******
System.ComponentModel.Win32Exception (0x80004005): system cannot find specified file
   in System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   in System.Diagnostics.Process.Start()
   in Edge_Remover.Form1.Form1_Load(Object sender, EventArgs e)
   in System.Windows.Forms.Form.OnLoad(EventArgs e)
   in System.Windows.Forms.Form.OnCreateControl()
   in System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   in System.Windows.Forms.Control.CreateControl()
   in System.Windows.Forms.Control.WmShowWindow(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   in System.Windows.Forms.Form.WmShowWindow(Message& m)
   in System.Windows.Forms.Form.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

follows a list of loaded modules:
mscorlib
Edge Remover
System.Windows.Forms
System
System.Drawing
System.Configuration
System.Core
System.Xml
System.Windows.Forms.resources
mscorlib.resources

Installed net 4..8.1 and 7, to no avail...

help please!

**Comment by jbara2002** [comment] 2023-01-18 15:34
i will post soon a new pre version... today or tommorow.. (which is fixing the problem due Edge Version Verification) plus partial code of.the gui

**Comment by jbara2002** [comment] 2023-01-18 22:34
solve in 
https://github.com/jbara2002/edge-remover/releases/tag/2.1

**Comment by caspertone2003** [comment] 2023-01-21 01:32
@jbara2002 
Thanks ... but still not running in my W10 21H2 deeply debloated... any idea of what I might be missing?

**Comment by jbara2002** [comment] 2023-01-21 11:35
thanks for noticing that.. last problem was the verification version of Edge Chromium when is removed..  (the error was the edge cannot be found).. i try to work some exceptions, if edge exists or not.
maybe the problem is from me or from you...
Had you removed Edge with this script before to run it again?

**Comment by caspertone2003** [comment] 2023-01-21 21:08
@jbara2002 
Thanks for answering.
I do not think the issue is actually on Edge removal, the exception happens before the selection box message (the gui) pops up; after "accepting" the error, the popup comes.
I did not try to continue the execution after the selection box pops up, as I am unsure what might behave ...

I attach what appears

![index](https://user-images.githubusercontent.com/4682903/213887154-75a0de38-eec4-48e9-9f6a-63a2cd89da11.jpg)

then, if I click on continue

![edgeremover](https://user-images.githubusercontent.com/4682903/213887196-6a322976-83d7-487e-a3c0-4f792338d871.PNG)

I stop there, as said, as I do not know what might have failed before....

**Comment by jbara2002** [comment] 2023-01-22 12:12
1.The Desktop , Taskbar and Start Menu icons are left, is not working and is was noted as know issue.
2. The Error is applying for Edge Version Verefication when Edge is not found in the System... Maybe moving from executable version to registry will solve the errors.
3. The Version 2.2 (preview) will launch next Thursday, or next Friday and will remove the dependency of TaskScheduler.dll , when removing the tasks (which is working), and solving the problem with desktop/start menu/taskbar icons.

**Comment by caspertone2003** [comment] 2023-01-22 14:55
@jbara2002 
Thanks for answering again.
I will not be able to test 2.2 in this PC, but will test in another...

after the dirty deletion of edge folders remaining, I detected an issue with winbio.dll missing, but cannot link that to edgeremoval.exe; causality or casualty? who knows?

**Comment by jbara2002** [comment] 2023-01-22 18:30
reinstall edge with winget to that pc

**Comment by caspertone2003** [comment] 2023-01-22 21:26
Not so easy...
I have no winget as I have removed many things. First thing, I try to run winget.exe without installation. Failure
Then I try to re-intall winget, for that I need to install its msix ... I tried with power shell but then Microsoft.UI.Xaml.2.7 is missing, as well as the store is missing.
Did not found a way to have winget running without reinstallng UI.Xaml
But looks it is possible, I found a how to here - [https://github.com/muradbuyukasik/winget-script](url)
Will report back. Easier ways are wellcomed!

**Comment by caspertone2003** [comment] 2023-01-24 01:50
@jbara2002 
Was not easy but done.
Just let the steps for anyone interested

In order to install Edge,
- locate winget
- run
winget install -e --id Microsoft.Edge 

not working? no winget? then... continue reading
=========================================================
I did this inside a CMD with admin rights and after moving to C:\Users\myuser\scoop\apps\winget\1.4.10173>

Locate your working winget and do as said above
mine ended there ... see next steps if you do not have winget
do you have an operational winget? test it! : open CMD admin and type winget enter
==================================

How I got an operational winget?
According to 
https://github.com/muradbuyukasik/winget-script
should be easy; not so in my case.

1 - Try to install winget this way:
- download the lastest release of  .msixbundle install and .xml license file from https://github.com/microsoft/winget-cli/releases
- Install in an Admin powershell with: Add-AppxProvisionedPackage -Online -PackagePath "PATH TO MSIXBUNDLE" -LicensePath "PATH TO XML" -Verbose
- Wait for the install to finish and you're done. You may need to restart the terminal, or reboot your pc.
- Verify that the installation succeeded by running winget in PowerShell. If no errors occur then you're done!
====================================================
If VC++ missing, you need to install it, then repeat above winget install.
If Microsoft.UI.Xaml.2.7 missing, you need to install it, then repeat above winget install
===============================================
Install VC++
- Get VC++ v14 Desktop Framework Package for your architecture,
from https://docs.microsoft.com/en-gb/troubleshoot/cpp/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages
- Install in Admin powershell with: Add-AppxPackage -Path "PATH TO FILE"
==============================================
Install Microsoft.UI.Xaml.2.7
- Download its Nuget package from https://www.nuget.org/packages/Microsoft.UI.Xaml/ manually by clicking "Download package" on the right hand side under the "About" section.
- Change the file extension from .nuget to .zip and expand it with any archiving program. (7zip does not need the renaming...)
- Within expanded folder navigate to tools\AppX\[YOUR ARCHITECTURE]\Release
-  extract Microsoft.UI.XAML.2.7.appx.
- Install in CMD powershell with: Add-AppxPackage -Path "PATH TO FILE"
=================================================
In my case, winget so installed was not functional, I got alwasy "access denied",
So, I had to try another way to get winget operational....
I followed method provided here:
https://github.com/microsoft/winget-cli/issues/1328#issuecomment-1208640211

Install scoop, in NON-admin powershell, execute
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser 
then execute
irm get.scoop.sh | iex

should you get a message that winget was installed sucessfully,...
search for your winget (in C;/Users/youruser/scoop
then open an admin CMD and finally run ...
winget install -e --id Microsoft.Edge 

=================================
Now you have Edge fully installed and its all associated folders.... ready to try with next incarnations of Edge-remover...

==================================
NOTE / CAVEAT - your own risk
I will not be able to answer questions on above. I just tried and tried, but I am unknowledgeable of all that mumbo jumbo; followed other instructions but really do not know what I was doing. It worked for me. Probably quite raw. Probably got a lot of rubbish to remove. Dont try it if you are uncomfortable. Do not try it if you are unable to use cmd,
etc.
==================================
Best approaches welcomed!!
It was the way I found to reinstall all removed elements from my extremely streamlined W10,
==================================
Thanks for Edge-remover!!!

CT

**Closed** 2023-02-01 15:55 UTC
Labels: wontfix
